config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/estacion'
  get 'home/estaciones'
  get 'home/municipios'
  post 'home/estacion' => 'home#estacion'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
    require 'net/http'
    require 'json'

    @url_oc = URI("https://opendata.aemet.es/opendata/api/observacion/convencional/todas?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdWJhbmliYWxAaG90bWFpbC5jb20iLCJqdGkiOiIyYTdkNWE1YS00YTM0LTRkYjEtOWUyMS1hZTBmMTZmMGM1ZjciLCJpc3MiOiJBRU1FVCIsImlhdCI6MTYyNjE5MTgyOSwidXNlcklkIjoiMmE3ZDVhNWEtNGEzNC00ZGIxLTllMjEtYWUwZjE2ZjBjNWY3Iiwicm9sZSI6IiJ9.WuQ4ezid3wNtsOhdC8zGLG5rJPbAmowBVJuNrFeXL_8")
    @uri_oc = URI(@url_oc)
    @response_oc = Net::HTTP.get(@uri_oc)
    @valores_oc = JSON.parse(@response_oc)
    @todas = @valores_oc["datos"]
    @uri2_todas = URI(@todas)
    @response2_todas = Net::HTTP.get(@uri2_todas)
    @valor_todas = JSON.parse(@response2_todas)

    



  end
  
  def estacion
    @idema = params['miform']
    if @idema
      require 'net/http'
      require 'json'

      @url_estacion = URI("https://opendata.aemet.es/opendata/api/observacion/convencional/datos/estacion/"+@idema+"?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdWJhbmliYWxAaG90bWFpbC5jb20iLCJqdGkiOiIyYTdkNWE1YS00YTM0LTRkYjEtOWUyMS1hZTBmMTZmMGM1ZjciLCJpc3MiOiJBRU1FVCIsImlhdCI6MTYyNjE5MTgyOSwidXNlcklkIjoiMmE3ZDVhNWEtNGEzNC00ZGIxLTllMjEtYWUwZjE2ZjBjNWY3Iiwicm9sZSI6IiJ9.WuQ4ezid3wNtsOhdC8zGLG5rJPbAmowBVJuNrFeXL_8")
      @uri_estacion = URI(@url_estacion)
      @response_estacion = Net::HTTP.get(@uri_estacion)
      @valores_estacion = JSON.parse(@response_estacion)
      @tiempo_estacion = @valores_estacion["datos"]
      @uri_tiempo_estacion = URI(@tiempo_estacion)
      @response2_estacion = Net::HTTP.get(@uri_tiempo_estacion)
      @valores2_estacion = JSON.parse(@response2_estacion)
    end

  end

  def estaciones
    require 'net/http'
    require 'json'

    @url = URI("https://opendata.aemet.es/opendata/api/valores/climatologicos/inventarioestaciones/todasestaciones/?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdWJhbmliYWxAaG90bWFpbC5jb20iLCJqdGkiOiIyYTdkNWE1YS00YTM0LTRkYjEtOWUyMS1hZTBmMTZmMGM1ZjciLCJpc3MiOiJBRU1FVCIsImlhdCI6MTYyNjE5MTgyOSwidXNlcklkIjoiMmE3ZDVhNWEtNGEzNC00ZGIxLTllMjEtYWUwZjE2ZjBjNWY3Iiwicm9sZSI6IiJ9.WuQ4ezid3wNtsOhdC8zGLG5rJPbAmowBVJuNrFeXL_8")
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @valores = JSON.parse(@response)
    @tiempo = @valores["datos"]
    @uri_tiempo = URI(@tiempo)
    @response2 = Net::HTTP.get(@uri_tiempo)
    @valores2 = JSON.parse(@response2)
    end
  
  def municipios
    require 'net/http'
    require 'json'

    @url_municipios = URI("https://opendata.aemet.es/opendata/api/maestro/municipios/?api_key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdWJhbmliYWxAaG90bWFpbC5jb20iLCJqdGkiOiIyYTdkNWE1YS00YTM0LTRkYjEtOWUyMS1hZTBmMTZmMGM1ZjciLCJpc3MiOiJBRU1FVCIsImlhdCI6MTYyNjE5MTgyOSwidXNlcklkIjoiMmE3ZDVhNWEtNGEzNC00ZGIxLTllMjEtYWUwZjE2ZjBjNWY3Iiwicm9sZSI6IiJ9.WuQ4ezid3wNtsOhdC8zGLG5rJPbAmowBVJuNrFeXL_8")
    @uri_municipios = URI(@url_municipios)
    @response_municipios = Net::HTTP.get(@uri_municipios)
    @valores_municipios = JSON.parse(@response_municipios)
    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Ozono', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <%= link_to 'Estacion', home_estacion_path, class:"nav-link" %>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Todas Estaciones', home_estaciones_path, class:"nav-link" %>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Municipios', home_municipios_path, class:"nav-link" %>
          
        </li>
        
        
      </ul>
      
      <%= form_tag  home_estacion_path, :method => 'POST' do %>
        <div class="d-flex">
          <%= text_field_tag 'miform', nil, placeholder:"Buscar", class:"form-control me-2" %>
     
          <%= submit_tag "Buscar", class:"btn btn-outline-light"  %>
        
       
          <% end %>
        </div>
  </div>
</nav>

app/views/home/estacion.html.erb
<% if @idema %>
	<% @valores2_estacion.each do |clave, valor| %>
	<div class="card text-center">
	  <div class="card-header">
	  	

		    <h1><%= clave["ubi"] %>- <%= clave["idema"] %></h1>

		  </div>
		  <div class="card-body">
		    <h5 class="card-title"><%= clave["fint"] %></h5>
		    Velocidad Viento :<%= clave["vv"] %> <br/>

		    <a href="#" class="btn btn-primary">Go somewhere</a>
		  </div>
		  <div class="card-footer text-muted">
		    2 days ago
		  </div>
	  <% end %>
</div>
<% end %>

app/views/home/estaciones.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Indicativo</th>
      <th scope="col">Nombre</th>
      <th scope="col">Provincia</th>
      <th scope="col">Altitud</th>
      <th scope="col">Latitud</th>
      <th scope="col">Longitud</th>
    </tr>
  </thead>
  <tbody>
    <% @valores2.each do |clave, valor| %>
    <tr>
      <th scope="row"><%= clave["indicativo"] %></th>
      <td><%= clave["nombre"] %></td>
      <td><%= clave["provincia"] %></td>
      <td><%= clave["altitud"] %></td>
      <td><%= clave["latitud"] %></td>
      <td><%= clave["longitud"] %></td>

     
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<% @valor_todas %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Idema</th>
      <th scope="col">Ubicación</th>
      <th scope="col">Prec</th>
      <th scope="col">Ta</th>
      <th scope="col">Latitud</th>
      <th scope="col">Longitud</th>
    </tr>
  </thead>
  <tbody>
    <% @valor_todas.each do |clave, valor| %>
    <tr>
      <th scope="row"><%= clave["idema"] %></th>
      <td><%= clave["ubi"] %></td>
      <td><%= clave["prec"] %></td>
      <td><%= clave["ta"] %></td>
      <td><%= clave["lat"] %></td>
      <td><%= clave["lon"] %></td>

     
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/municipios.html.erb
<% @valores_municipios %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Capital</th>
      <th scope="col">Nº Habitantes</th>
      <th scope="col">Latitud</th>
      <th scope="col">Longitud</th>
    </tr>
  </thead>
  <tbody>
    <% @valores_municipios.each do |clave, valor| %>
    <tr>
      <th scope="row"><%= clave["id"] %></th>
      <td><%= clave["nombre"] %></td>
      <td><%= clave["capital"] %></td>
      <td><%= clave["num_hab"] %></td>
      <td><%= clave["latitud_dec"] %></td>
      <td><%= clave["longitud_dec"] %></td>

     
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozono</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>